### PR TITLE
Enable setting FILTER on variant records

### PR DESCRIPTION
**Pull request by chapmanb**
Brent;
I'm using cyvcf2 to update filters (providing a VCF file of germline variants from those filtered by a standard somatic tumor/normal pipeline). This enables setting the filters provided a list of filter names that exist in the header. Longer term it would be great to also be able to add new filters, but this works for my immediate needs. I'd be happy for any checks on this as I'm not too experiences with cython. Thanks much.

### CODE REVIEW

**Comment by chapmanb** [comment]
If this all looks good it would be great to roll a new version and updated conda package so I can depend on it. I'm happy to help with the conda package, or any other bits that would make it easier.

**Comment by danielecook** [comment]
Along these lines - I've been using cyvcf2 to add new filters to a VCFs including updating the header - both for site filters and genotype filters. It would be nice to be able to edit/add headers.

**Comment by brentp** [comment]
thanks Brad, I will update the bioconda recipe. I might make it check if filters is basestring and then wrap it as a list.
@danielecook I'd love to have that functionality, but just haven't gotten around to it.

**Comment by chapmanb** [comment]
Brent -- awesome, thanks so much. The basestring check would be great. That was beyond my cython skill level so I'll be anxiously awaiting the code so I can try to level up. Thanks again.

**Comment by brentp** [comment]
This is pending CI checks on bioconda. Brad and/or @danielecook if you open a ticket for updating the header, it's more likely to get added... but no promises.

**Comment by chapmanb** [comment]
Awesome, thanks Brent. I can't believe you only needed to write python code for that -- sorry, I totally should have added it in. cython is magic. Much appreciated.

**Comment by brentp** [comment]
yeah, cython is magic, but you did the hard part. this is up on bioconda now.

**Pull request merged**
