### PR TITLE
Update htslib; fix configure bug + enable s3 htslib

### PR DESCRIPTION
**Pull request by splichte**
Please let me know if there's anything you'd like me to change.

### CODE REVIEW

**Comment by splichte** [comment]
Updated.

**Comment by brentp** [comment]
hmm. I should have checked this closer. Did you update the submodule or pull in new code? I'm confused about what happened here.

**Comment by brentp** [comment]
ok. I see. I thought I had htslib as a submodule. Apparently not. Thanks for the update.

**Comment by splichte** [comment]
Would you prefer it to be a submodule instead?

**Comment by brentp** [comment]
that would be great! I already merged your PR, but I think having htslib as a submodule would be an improvement if you're up for it.

**Comment by splichte** [comment]
sure, I'll take a look at it! I noticed though in one of your commit messages you had "include htslib in source tree to ease install". do you remember if you ran into any particular problems with installing when you tried it another way?

**Comment by brentp** [comment]
I don't recall exactly, it was probably a simple fix when htslib used to be easier to build, but I think a submodule would be better now.

**Pull request merged**
