### PR TITLE
Make quality settable

### PR DESCRIPTION
**Pull request by ernfrid**
I've written some code relying on this change and thought it might be useful to contribute back. As far as I could tell there didn't need to be any documentation changes, but do let me know if additional changes are needed.

### CODE REVIEW

**Comment by brentp** [comment]
can you force it to be int (or uint8) in the signature? and/or what happens if you send in a non-int?

**Comment by ernfrid** [comment]
Looks like it should be a float, right? I hadn't played with types (and hadn't noticed an issue). I'll look into that.

**Comment by brentp** [comment]
you're right. a float. it might be that the error message for e.g. a string is good enough, I just cant remember what happens .

**Comment by ernfrid** [comment]
Looks like we get: `TypeError: a float is required` which seemed ok to me at first blush.

I added a test.

**Comment by ernfrid** [comment]
It would be nice to make it able to clear the QUAL (e.g. by passing None), but I haven't been able to figure out how to set the missing value. Setting `self.b.qual = bcf_float_missing` results in a large floating point number.

**Comment by ernfrid** [comment]
Fixed this by adding `bcf_float_set` to cyvcf2.pxd and using that to set the value.

**Comment by brentp** [comment]
cheers

**Pull request merged**
