### PR TITLE
Handle missing dependencies for package setup/build

### PR DESCRIPTION
**Pull request by juliangehring**
Currently, the package setup requires the build dependencies `numpy` and `cython`to be already installed when trying to install `cyvcf2`. As an example, `pip install cyvcf2` with either one of the dependencies missing fails with an `ImportError`. The issue arises since setuptools requires parsing `setup.py` once before any install occurs, in order to detect the dependency structure.

This patch allows missing dependencies when parsing `setup.py`, and separates a) installing missing dependencies and b) build extensions which require these dependencies to be present.

### CODE REVIEW

**Comment by juliangehring** [comment]
This should also fix the issues raised in #25.

There are different approach to this, but I found this one to be the most direct with the existing setup structure.

**Comment by brentp** [comment]
thanks very much.

**Comment by juliangehring** [comment]
@brentp Do you think it as worth tagging a new release version of pypi with these changes? Then `pip install cyvcf2` will work out of the box as advertised.

**Comment by brentp** [comment]
done. thanks for the reminder.

**Pull request merged**
