### PR TITLE
Support mixed ploidy VCF files for gt_bases

### PR DESCRIPTION
**Pull request by chapmanb**
This is a fix for arq5x/gemini#431, where GEMINI will error out in
cyvcf2 if the input file has mixed ploidies. This happens in bcbio when
calling X, Y and MT for human and also when callers are too lazy to
output two alleles for a reference.

### CODE REVIEW

**Comment by brentp** [comment]
awesome. thanks! I'll merge once travis is finished.

we still don't support haploid X in gemini.

**Comment by chapmanb** [comment]
Awesome, thanks for jumping on this so fast. I'm mostly trying to avoid bcbio choking on GEMINI step for any of these complicated cases, I know support for this sort of VCF craziness is still in progress. Whenever you think you're ready for 0.4.1 I can roll a new bioconda package. Thanks again.

**Comment by brentp** [comment]
I bumped and have the PR in to bioconda: https://github.com/bioconda/bioconda-recipes/pull/1870
we'll be making a the 0.19.0 gemini release as well.

**Comment by chapmanb** [comment]
You are the best. Thanks so much.

**Pull request merged**
