### PR TITLE
Adds property end_chrom and parse correct end position for BNDs. Fix …

### PR DESCRIPTION
**Pull request by moonso**
…brentp/cyvcf2/#65

### CODE REVIEW

**Comment by brentp** [comment]
I'm not sold on this as it adds an INFO lookup for every call to `.end` which is otherwise a very cheap call for a rare use-case.

I think this might be better as a separate function and might be outside the scope of cyvcf2. what do you think?

**Comment by brentp** [comment]
ping @moonso, though the more I think about this, the less I like the idea of its inclusion. I think this is fine as a user-function. otherwise, the API surface area of cyvcf2 will continue to grow indefinitely.
thoughts?

**Comment by moonso** [comment]
Ok I see your point, the idea was that when you start to use properties you would not expect cyvcf to be as fast.
I can add it as a new property like you mention? Could call it `sv_end` or `true_end`?

**Comment by moonso** [comment]
What do you think @brentp ?

**Comment by moonso** [comment]
Ok, let's skip this one 👍

**Pull request closed without merging**
