### PR TITLE
Support for phased genotypes as numpy arrays

### PR DESCRIPTION
**Pull request by jeffspence**
Added getting and setting phased genotypes as numpy arrays using the property numpy_genotypes.

variant.numpy_genotypes returns 2 numpy arrays.  The first is a num_samples by max_ploidy int array, where each entry is an individual's allele (-1 if missing, -2 is absent [i.e. that individual has ploidy less than max_ploidy]).  The second array is a 1d bool array of size num_samples, indicating whether or not each sample is phased.

Setting is also supported given that variant.numpy_genotypes is set to be a tuple of two arrays as described above.  i.e.
variant1.numpy_genotypes = variant2.numpy_genotypes
will cause variant1 to have the same phased genotypes as variant2.

getting and setting either the numpy_genotypes or the genotypes properties will result in both being set to the correct, new value.

### CODE REVIEW

**Comment by brentp** [comment]
this looks nice. could you replicate the current tests for phasing on this new method? And can you verify that this does improve the performance?

this highlights a growing problem with cyvcf2 -- that the Variant object, which should be light-weight. Is getting a large number of things attached to it. I think I may remove the caching for the .genotypes method and see what else can be culled. Thoughts?

This is handled much more nicely in [hts-nim](https://github.com/brentp/hts-nim) where I learned from my mistakes in cyvcf2.

Finally, can we think of a name other than numpy_genotypes?

**Comment by jeffspence** [comment]
Here's some timing bench marks on a vcf with ~1M variants for 99 individuals.  (10 replicates for each)
numpy_genotypes:
`
for variant in VCF('data.vcf.gz'):
    variant.numpy_genotypes
`
mean: 16.1s (min: 15.0, max: 18.9s)

genotypes:
`
for variant in VCF('data.vcf.gz'):
    variant.genotypes
`
mean: 22.7s (min: 22.2s, max: 24.0s)

So it looks like there's about a ~30% speed up (not counting any downstream massaging from lists into numpy arrays, which for the application that I have where I need haplotypes in a numpy array results in about a ~3x speedup).

Indeed:
genotypes (plus converting to numpy):
`
for variant in VCF('data.vcf.gz'):
    np.array(variant.genotypes)
`
mean: 64.0s (min: 26.1s, max: 74.0s) [I'm not sure why there's so much variance]
so if numpy arrays are needed downstream then there's a 4x speedup.


I'll push some tests in a bit.

In terms of the Variant object, I agree with removing the caching of .genotypes (and .numpy_genotypes).  My use case (and I assume the standard use case) will be just iterating over variants in the VCF and pulling out the useful bits, so there's no need to store these objects.

Totally agreed about the name.  In #31 you mentioned calling this functionality numpy_genotypes so I went with that, but I think there are definitely better ones.  Maybe genotype_arrays or phased_genotype_arrays or something along those lines.  Your call.

**Comment by brentp** [comment]
this is a pretty modest speedup for this much code duplication. Is there a way we can make `.genotypes` return a numpy record array that matches fairly closely the current implementation, but that has (most of) the speed of this change?

**Comment by brentp** [comment]
I am working on a version that uses a rec-array. it won't be exactly compatible with the current version, but should be a good compromise with speed and code.

**Comment by brentp** [comment]
well, using structured arrays makes this even slower (though would prevent you from converting to numpy array). I think the slowness in converting to a numpy array is because it's not a fixed type so it has to make an object array. Let me think about what to do. Sorry for encouraging you to implement and then stalling, it's just, as I mentioned, that it highlights some growing pains in this project.

**Comment by jeffspence** [comment]
I agree that creating object arrays in numpy is not the way to go.

One possibility would be to return an array that maps genotypes like:

`
['0|0', '0/1', '0'] --> np.array(
    [[0, 0, 1],
     [0, 1, 0],
     [0, -2, 1]],
    dtype = np.int32)
`

That way 0 in the final column evaluates to False as before and 1 evaluates to True as before.  The fact that they are of fixed length will break backward compatibility, though.  It _would_ be possible to allow the `genotypes.__set__` to take either an array of this shape, or a list in the old format and update the genotypes accordingly (e.g. by inserting the right number of -2 if the length of a given inner list was less than the max length).

Another possibility is to keep `numpy_genotypes` as is (with a name change) and then change `genotypes.__get__` to be a very thin wrapper for `numpy_genotypes.__get__` that just performs a list comprehension along the lines of
`return [gt[gt > -2].tolist() + [phase] for gt, phase in self.numpy_genotypes]`
which would cut down on code duplication.

**Comment by brentp** [comment]
I think I have a way to do this that will have good performance and nice usage. I just need to carve out some time to work on it. I'll try to get to it next week. Sorry for the delay.

**Comment by jeffspence** [comment]
Great!  Thanks!

**Comment by brentp** [comment]
@jeffspence I think: https://github.com/brentp/cyvcf2/commit/9ed80c0f05052b61da1979bb55c99c43d277d698
is a good approach. It needs more work for setting, but it should be pretty fast and intuitive for getting (just have a look at the tests).

happy to hear any feedback.

**Comment by brentp** [comment]
I have now added the ability to set phase and allele. All that remains is to propagate it back to the VCF using bcf_update_genotypes on Genotypes._raw.

**Comment by brentp** [comment]
ok. that branch now has a full implementation (I think).
@jeffspence would you give it a try?

**Comment by brentp** [comment]
here is the branch: https://github.com/brentp/cyvcf2/tree/genotype-objects

**Comment by jeffspence** [comment]
@brentp sorry for the delay.  Maybe I'm missing something, but I'm not sure how this helps get the phased genotypes into a numpy array quickly.  Here are my timing results on an arbitrary, big VCF repeated 3 times.  I need to get the phased genotypes into one array (n x 2) and the phasings into another.  If I do this I get the following timings

original (i.e. old commit):
```
import numpy as np
from cyvcf2 import VCF


for variant in VCF('data.vcf.gz'):
    genos, phased = variant.genotypes
    genos = np.array([gt[0:2] for gt in gts])
    phased = np.array([gt[-1] for gt in gt_list])
```
Timings: 2m36.779s, 2m36.039s, 2m42.184s


numpy_genotypes:
```
import numpy as np
from cyvcf2 import VCF


for variant in VCF('data.vcf.gz'):
    genos, phased = variant.numpy_genotypes
```
Timings: 0m32.795s, 0m31.190s, 0m31.890s


genotype-objects:
```
import numpy as np
from cyvcf2 import VCF


vcf_file = VCF('data.vcf.gz')
n = len(vcf_file.samples)
for variant in vcf_file:
    gts = variant.genotype
    genos = np.array([gts.alleles(k) for k in range(n)])
    phased = np.array([gts.phased(k) for k in range(n)])
```
Timings: 3m19.578s, 3m23.163s, 3m19.886


So it looks like the speed for the new implementation is ~20% worse than the old implementation using lists and ~500% worse than the numpy_genotypes implementation, unless I'm missing something.

**Comment by brentp** [comment]
I'd have to see more about your actual use-case. The object returned from variant.genotypes returns an efficient representation of the genotypes. You'll probably get better performance from it if you set the phase and/or alts directly, e.g.:
```
    gts = variant.genotype
    gts[0][0].phased = True
```
If you just need to create a numpy array, then maybe we could add `__array_interface__` to the Genotypes object.

**Comment by jeffspence** [comment]
I apologize for not being clear -- the part that is the bottleneck right now is taking the list of genotypes and getting it into a numpy array.  I'm less concerned with the minor overhead in cyvcf2.  What would be ideal, would be to get the phased haplotypes in a numpy array directly from cyvcf2 (i.e., a la numpy_genotypes).

At the end of the day, I want a 2d numpy array that is 2*n_samples x n_loci, where entry (i, j) is the allele of haplotype i at position j (maybe while doing some filtering).  I want to treat unphased data as being missing.

**Comment by brentp** [comment]
So, the Genotypes object has an underlying `_raw` attribute. If you want to make a PR to make your arrays available from that, I'd likely accept. Then it's not polluting the variant object, it's on the genotypes object where it's more likely to be seen and used by those that need it.

I still would like to see the real use-case becaues if you just need the genotypes and phases, you can use `gt_types` and `gt_phase`

**Comment by jeffspence** [comment]
```gt_types``` won't work for me because it is unphased.  I need to know which allele at one locus is on the same haplotype as some allele at another locus, so treating '0|1' and '1|0' the same won't work.

I'll work on it if I get around to it.

**Comment by jeffspence** [comment]
@brentp okay -- I took a stab at implementing getting the genotypes and phase as numpy objects.  They are now methods of the Genotypes object.  I added some tests to show how they work.

**Comment by jeffspence** [comment]
I should note that for the tests above, I get runtimes comparable to my old implementation:

```      
for variant in VCF('data.vcf.gz'):
    gts = variant.genotype
    genos = gts.alleles_array()
    phased = gts.phased_array()
```

results in runtimes of 0m33.416s, 0m31.977s, 0m31.684s

**Comment by brentp** [comment]
ok. thanks for re-implementing. I apologize for giving you the run-around on this, but I think this is a cleaner solution. I may play around with the API a bit, but I will ping this PR if it changes.

**Pull request merged**
