### PR TITLE
 add alternative genotypes array impl

### PR DESCRIPTION
**Pull request by brentp**
@jeffspence would you take a look.
This is a tiny bit faster. I like this because it matches the type returned from variant.genotypes, but otherwise, I'll defer to your thoughts on if you think this should replace Genotypes.allles_array and phased_array.

### CODE REVIEW

**Comment by jeffspence** [comment]
@brentp -- This looks good to me.  I can make either work, so if you want to replace Genotypes.alleles_array and Genotypes.phased_array by Genotypes.array that is fine by me.

**Comment by brentp** [comment]
ok. thank you. I updated the tests and merged.

**Comment by jeffspence** [comment]
Great!  Thanks for this.

**Comment by brentp** [comment]
thank you!

**Pull request merged**
